#!/usr/bin/env node
/**
 * Generate stage-specific env files from CDK outputs.
 *
 * Usage (via justfile):
 *   just outputs-env stage=<stage> target=<target>
 *
 * Direct usage:
 *   pnpm --filter @agentra/infra-cdk exec tsx ../../scripts/agent/generate-env.ts \
 *     --stage <stage> --target <target>
 *
 * Targets:
 *   frontend-local    - Next.js at localhost:3000; API at localhost:8080 (api-local mode)
 *   frontend-api-cloud - Next.js at localhost:3000; API from CDK outputs (api-cloud mode)
 *   api-local         - Hono backend at localhost:8080 against cloud DynamoDB/Cognito/AgentCore
 *   agent-local       - Local AgentCore runtime process against cloud KB/Bedrock
 *   kb-smoke          - Knowledge Base smoke scripts
 *   bff-smoke         - BFF /chat SSE endpoint smoke test (just smoke-bff-chat)
 *
 * Inputs:  .agentra/outputs/<stage>.json  (written by just cdk-deploy-with-outputs)
 * Outputs: .agentra/env/<stage>/<target>.env  (gitignored)
 *
 * Secret values are never written — only ARN references and non-sensitive config.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// Resolve paths from the repo root regardless of which directory tsx is invoked from.
const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');

type Target =
  | 'frontend-local'
  | 'frontend-api-cloud'
  | 'api-local'
  | 'agent-local'
  | 'kb-smoke'
  | 'bff-smoke';

const VALID_TARGETS: readonly Target[] = [
  'frontend-local',
  'frontend-api-cloud',
  'api-local',
  'agent-local',
  'kb-smoke',
  'bff-smoke',
];

type StackOutputs = Record<string, string>;
type CdkOutputs = Record<string, StackOutputs>;

// ── arg parsing ──────────────────────────────────────────────────────────────

function parseArgs(): { stage: string; target: Target } {
  const args = process.argv.slice(2);
  let stage = '';
  let target = '';

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--stage' && args[i + 1]) {
      stage = args[++i] ?? '';
    } else if (args[i] === '--target' && args[i + 1]) {
      target = args[++i] ?? '';
    }
  }

  if (!stage) {
    die('--stage <stage> is required');
  }
  if (!target) {
    die(`--target <target> is required. Valid targets: ${VALID_TARGETS.join(', ')}`);
  }
  if (!(VALID_TARGETS as readonly string[]).includes(target)) {
    die(`unknown target '${target}'. Valid targets: ${VALID_TARGETS.join(', ')}`);
  }

  return { stage, target: target as Target };
}

// ── outputs loading ───────────────────────────────────────────────────────────

function loadOutputs(stage: string): CdkOutputs {
  const outputsPath = resolve(REPO_ROOT, `.agentra/outputs/${stage}.json`);
  let raw: string;
  try {
    raw = readFileSync(outputsPath, 'utf8');
  } catch {
    die(
      `outputs file not found: ${outputsPath}\n` +
        `       Run: just cdk-deploy-with-outputs <group> ${stage}`,
    );
  }
  try {
    return JSON.parse(raw) as CdkOutputs;
  } catch {
    die(`malformed JSON in ${outputsPath}`);
  }
}

function getStack(
  outputs: CdkOutputs,
  stackBaseName: string,
  stage: string,
): StackOutputs {
  const stackId = `${stackBaseName}-${stage}`;
  const stack = outputs[stackId];
  if (!stack) {
    die(
      `stack '${stackId}' not found in outputs.\n` +
        `       Deploy the group containing ${stackBaseName}:\n` +
        `         just cdk-deploy-with-outputs <group> ${stage}`,
    );
  }
  return stack;
}

function maybeStack(
  outputs: CdkOutputs,
  stackBaseName: string,
  stage: string,
): StackOutputs | undefined {
  return outputs[`${stackBaseName}-${stage}`];
}

// ── env builders ──────────────────────────────────────────────────────────────

// Single-quote a value for safe use with `set -a; source`.
// Handles embedded single quotes via the '\'' idiom.
function shellQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

function line(key: string, value: string | undefined): string {
  return value ? `${key}=${shellQuote(value)}` : `# ${key}=`;
}

function requiredLine(key: string, value: string | undefined, stackName: string): string {
  if (!value) {
    die(
      `required output '${key}' is missing from ${stackName} stack outputs — stack may be out of date`,
    );
  }
  return `${key}=${shellQuote(value)}`;
}

function header(stage: string, target: Target, usage: string): string {
  return [
    `# Generated by: just outputs-env stage=${stage} target=${target}`,
    `# Stage: ${stage}`,
    `# ${usage}`,
  ].join('\n');
}

function buildFrontendLocal(outputs: CdkOutputs, stage: string): string {
  const auth = getStack(outputs, 'AgentraDataAuthStack', stage);
  return [
    header(stage, 'frontend-local', 'Usage: copy to apps/frontend/.env.local'),
    'NEXT_PUBLIC_API_MODE=real',
    'NEXT_PUBLIC_API_BASE_URL=http://localhost:8080',
    'NEXT_PUBLIC_STREAMING_API_BASE_URL=http://localhost:8080',
    requiredLine(
      'NEXT_PUBLIC_COGNITO_USER_POOL_ID',
      auth.UserPoolId,
      'AgentraDataAuthStack',
    ),
    requiredLine(
      'NEXT_PUBLIC_COGNITO_CLIENT_ID',
      auth.UserPoolClientId,
      'AgentraDataAuthStack',
    ),
    requiredLine(
      'NEXT_PUBLIC_COGNITO_DOMAIN',
      auth.CognitoDomain,
      'AgentraDataAuthStack',
    ),
    'NEXT_PUBLIC_APP_URL=http://localhost:3000',
  ].join('\n');
}

function buildFrontendApiCloud(outputs: CdkOutputs, stage: string): string {
  const auth = getStack(outputs, 'AgentraDataAuthStack', stage);
  const app = getStack(outputs, 'AgentraAppStack', stage);
  return [
    header(stage, 'frontend-api-cloud', 'Usage: copy to apps/frontend/.env.local'),
    'NEXT_PUBLIC_API_MODE=real',
    requiredLine('NEXT_PUBLIC_API_BASE_URL', app.HttpApiUrl, 'AgentraAppStack'),
    requiredLine(
      'NEXT_PUBLIC_STREAMING_API_BASE_URL',
      app.StreamingApiUrl,
      'AgentraAppStack',
    ),
    requiredLine(
      'NEXT_PUBLIC_COGNITO_USER_POOL_ID',
      auth.UserPoolId,
      'AgentraDataAuthStack',
    ),
    requiredLine(
      'NEXT_PUBLIC_COGNITO_CLIENT_ID',
      auth.UserPoolClientId,
      'AgentraDataAuthStack',
    ),
    requiredLine(
      'NEXT_PUBLIC_COGNITO_DOMAIN',
      auth.CognitoDomain,
      'AgentraDataAuthStack',
    ),
    'NEXT_PUBLIC_APP_URL=http://localhost:3000',
  ].join('\n');
}

function buildApiLocal(outputs: CdkOutputs, stage: string): string {
  const auth = getStack(outputs, 'AgentraDataAuthStack', stage);
  const runtime = maybeStack(outputs, 'AgentraAgentCoreRuntimeStack', stage);
  const kb = maybeStack(outputs, 'AgentraBedrockKbStack', stage);

  const lines = [
    header(
      stage,
      'api-local',
      'Usage: just dev-backend-local <stage>  (sources this file automatically)',
    ),
    'HOST=127.0.0.1',
    'PORT=8080',
    'STORE_TYPE=dynamo',
    'BEDROCK_REGION=ap-northeast-1',
    requiredLine('THREADS_TABLE_NAME', auth.ThreadsTableName, 'AgentraDataAuthStack'),
    requiredLine('MESSAGES_TABLE_NAME', auth.MessagesTableName, 'AgentraDataAuthStack'),
    requiredLine('USERS_TABLE_NAME', auth.UsersTableName, 'AgentraDataAuthStack'),
    requiredLine('COGNITO_USER_POOL_ID', auth.UserPoolId, 'AgentraDataAuthStack'),
    requiredLine(
      'COGNITO_USER_POOL_CLIENT_ID',
      auth.UserPoolClientId,
      'AgentraDataAuthStack',
    ),
    'COGNITO_REGION=ap-northeast-1',
    'ALLOWED_CORS_ORIGINS=http://localhost:3000',
  ];

  if (runtime?.AgentCoreRuntimeArn) {
    lines.push(line('AGENTCORE_RUNTIME_ARN', runtime.AgentCoreRuntimeArn));
    lines.push('AGENTCORE_RUNTIME_QUALIFIER=prod');
  }

  if (kb?.BedrockKbId) {
    lines.push(line('BEDROCK_KB_ID', kb.BedrockKbId));
    lines.push(line('BEDROCK_KB_REGION', kb.BedrockKbRegion));
  }

  return lines.join('\n');
}

function buildAgentLocal(outputs: CdkOutputs, stage: string): string {
  const runtime = maybeStack(outputs, 'AgentraAgentCoreRuntimeStack', stage);
  const kb = maybeStack(outputs, 'AgentraBedrockKbStack', stage);

  const lines = [
    header(
      stage,
      'agent-local',
      'Usage: set env vars before running local AgentCore process',
    ),
    'BEDROCK_REGION=ap-northeast-1',
  ];

  if (kb?.BedrockKbId) {
    lines.push(line('BEDROCK_KB_ID', kb.BedrockKbId));
    lines.push(line('BEDROCK_KB_REGION', kb.BedrockKbRegion));
  }

  if (runtime?.AgentCoreRuntimeArn) {
    lines.push(line('AGENTCORE_RUNTIME_ARN', runtime.AgentCoreRuntimeArn));
  }

  return lines.join('\n');
}

function buildKbSmoke(outputs: CdkOutputs, stage: string): string {
  const kb = getStack(outputs, 'AgentraBedrockKbStack', stage);
  return [
    header(stage, 'kb-smoke', 'Usage: source before running KB smoke scripts'),
    requiredLine('BEDROCK_KB_ID', kb.BedrockKbId, 'AgentraBedrockKbStack'),
    requiredLine('BEDROCK_KB_REGION', kb.BedrockKbRegion, 'AgentraBedrockKbStack'),
  ].join('\n');
}

function buildBffSmoke(outputs: CdkOutputs, stage: string): string {
  const app = getStack(outputs, 'AgentraAppStack', stage);
  return [
    header(
      stage,
      'bff-smoke',
      'Usage: auto-loaded by just smoke-bff-chat / smoke-bff-chat-logs',
    ),
    requiredLine(
      'AGENTRA_STREAMING_API_BASE_URL',
      app.StreamingApiUrl,
      'AgentraAppStack',
    ),
    requiredLine('AGENTRA_API_BASE_URL', app.HttpApiUrl, 'AgentraAppStack'),
  ].join('\n');
}

// ── main ─────────────────────────────────────────────────────────────────────

function main(): void {
  const { stage, target } = parseArgs();
  const outputs = loadOutputs(stage);

  let content: string;
  switch (target) {
    case 'frontend-local':
      content = buildFrontendLocal(outputs, stage);
      break;
    case 'frontend-api-cloud':
      content = buildFrontendApiCloud(outputs, stage);
      break;
    case 'api-local':
      content = buildApiLocal(outputs, stage);
      break;
    case 'agent-local':
      content = buildAgentLocal(outputs, stage);
      break;
    case 'kb-smoke':
      content = buildKbSmoke(outputs, stage);
      break;
    case 'bff-smoke':
      content = buildBffSmoke(outputs, stage);
      break;
  }

  const outDir = resolve(REPO_ROOT, `.agentra/env/${stage}`);
  const outFile = join(outDir, `${target}.env`);

  mkdirSync(outDir, { recursive: true });
  writeFileSync(outFile, `${content}\n`, 'utf8');

  console.log(`Generated: ${outFile}`);
  console.log('');
  console.log(content);
}

// ── helpers ───────────────────────────────────────────────────────────────────

function die(message: string): never {
  console.error(`ERROR: ${message}`);
  process.exit(1);
}

main();
