import {
  type ArtifactManifest,
  artifactManifestSchema,
  buildDeckPreviewEvents,
  type DeckResult,
  deckResultSchema,
} from '@agentra/agent-tools';
import { BedrockAgentCoreApp } from 'bedrock-agentcore/runtime';
import { uuidv7 } from 'uuidv7';
import { buildRouterPrompt, createRouterAgent } from './agents/router/index.js';
import { buildLoggerOptions } from './logging.js';
import { createRuntimeSessionManager } from './memory/session-manager-factory.js';
import { ObservationCollector } from './observability.js';
import { RequestSchema } from './request-schema.js';
import { RuntimeLogger } from './runtime-logger.js';
import { createDeckMergedStream } from './tools/deck-merge.js';
import type { SubAgentProgressEvent } from './tools/invoke-manufacturing-line-agent.tool.js';

// Opt-in (default off): relay the slide-runtime's real-time deck-progress events
// (Epic #421) instead of replaying the completed deck at the end (Route A).
const ROUTER_DECK_STREAMING = process.env.ROUTER_DECK_STREAMING === 'true';

/**
 * Walk a tool-result content structure and yield every plain object that could
 * carry a structured payload, regardless of how the Strands SDK wrapped it.
 *
 * Live (#403) the SDK surfaced the slide tool's
 * `content: [{ text: JSON.stringify(payload) }]` as a nested
 * `[{ type: 'json', json: { status, content: [{ text }] } }]` — i.e. the tool's
 * *return object* (not the inner payload), with the deck buried two levels down.
 * Rather than hard-code one shape, this bounded walk descends through arrays,
 * `json` blocks, JSON-valued `text` strings, and nested `content` arrays so a
 * matcher can find its target wherever it ends up.
 */
function* walkToolResultObjects(
  value: unknown,
  depth = 0,
): Generator<Record<string, unknown>> {
  if (depth > 6 || value === null) return;
  if (Array.isArray(value)) {
    for (const item of value) yield* walkToolResultObjects(item, depth + 1);
    return;
  }
  if (typeof value === 'string') {
    const trimmed = value.trim();
    if (trimmed.startsWith('{') || trimmed.startsWith('[')) {
      try {
        yield* walkToolResultObjects(JSON.parse(trimmed), depth + 1);
      } catch {
        // not JSON — ignore
      }
    }
    return;
  }
  if (typeof value === 'object') {
    const rec = value as Record<string, unknown>;
    yield rec;
    // Descend into the SDK/tool wrapper fields that can nest the real payload.
    if ('json' in rec) yield* walkToolResultObjects(rec.json, depth + 1);
    if ('text' in rec) yield* walkToolResultObjects(rec.text, depth + 1);
    if ('content' in rec) yield* walkToolResultObjects(rec.content, depth + 1);
  }
}

/** Find the first object in a tool result that validates under `schema`. */
function findInToolResult<T>(
  content: unknown,
  schema: { safeParse: (v: unknown) => { success: true; data: T } | { success: false } },
  pick: (o: Record<string, unknown>) => unknown,
): T | undefined {
  for (const obj of walkToolResultObjects(content)) {
    const candidate = pick(obj);
    if (candidate === undefined) continue;
    const parsed = schema.safeParse(candidate);
    if (parsed.success) return parsed.data;
  }
  return undefined;
}

function parseArtifactManifestContent(content: unknown): ArtifactManifest | undefined {
  return findInToolResult(content, artifactManifestSchema, (o) => o);
}

/**
 * Extract a validated DeckResult from a `create_slide_presentation` tool result.
 *
 * Captured deterministically (the LLM never copies the presigned-URL payload)
 * and attached to the artifact manifest. Robust to the SDK's content wrapping
 * (see {@link walkToolResultObjects}).
 */
export function parseDeckFromSlideResult(content: unknown): DeckResult | undefined {
  return findInToolResult(content, deckResultSchema, (o) =>
    'deck' in o ? o.deck : undefined,
  );
}

/** Attach a captured deck to a manifest without clobbering an existing one. */
export function attachDeckToManifest(
  manifest: ArtifactManifest,
  deck: DeckResult | undefined,
): ArtifactManifest {
  if (!deck || manifest.deck) return manifest;
  return { ...manifest, deck };
}

/** Default pacing between replayed deck slide events (ms); 0 disables. */
const DECK_PREVIEW_REPLAY_PACING_MS = (() => {
  const raw = Number.parseInt(process.env.DECK_PREVIEW_REPLAY_PACING_MS ?? '200', 10);
  return Number.isFinite(raw) && raw >= 0 ? raw : 200;
})();

const sleep = (ms: number): Promise<void> =>
  ms > 0 ? new Promise((resolve) => setTimeout(resolve, ms)) : Promise.resolve();

/**
 * Stream Deck Preview progress for a captured deck as wrapped runtime SSE events
 * (Epic #403, Route A — deterministic replay). The deck is fully generated by
 * the time we replay, so a small pace between slide events gives the SDPM-like
 * "slides appear one by one" reveal without the LLM ever touching the payload.
 *
 * Pure relative to the deck (no I/O beyond the injectable pacing); degradable —
 * an empty/odd deck simply yields started + completed.
 */
export async function* emitDeckProgressEvents(
  deck: DeckResult,
  options: { paceMs?: number; sleepFn?: (ms: number) => Promise<void> } = {},
): AsyncGenerator<{ event: 'message'; data: { type: 'deck_progress'; event: unknown } }> {
  const paceMs = options.paceMs ?? DECK_PREVIEW_REPLAY_PACING_MS;
  const sleepFn = options.sleepFn ?? sleep;
  const events = buildDeckPreviewEvents(deck);

  for (const event of events) {
    yield { event: 'message', data: { type: 'deck_progress', event } };
    // Pace only between per-slide reveals, not after started/before completed.
    if (event.type === 'deck_slide_compose_ready') {
      await sleepFn(paceMs);
    }
  }
}

export type {
  ManufacturingLineAgentConfig,
  ManufacturingLineAgentResult,
  ManufacturingLineModelConfig,
} from './agents/manufacturing-line/index.js';
export { createManufacturingLineAgent } from './agents/manufacturing-line/index.js';
export type {
  RouterAgentConfig,
  RouterModelConfig,
  RouterPromptInput,
  RouterToneKey,
} from './agents/router/index.js';
export { buildRouterPrompt, createRouterAgent } from './agents/router/index.js';
export type {
  WebResearchAgentConfig,
  WebResearchAgentHandoffInput,
  WebResearchAgentHandoffOutput,
  WebResearchAgentResult,
  WebResearchModelConfig,
} from './agents/web-research/index.js';
export { createWebResearchAgent } from './agents/web-research/index.js';

type ModelKey = 'opus' | 'sonnet' | 'haiku';
type ResponsePreset = 'fast' | 'balanced' | 'deep';
type LengthKey = 'short' | 'normal' | 'detailed';

const MODEL_IDS: Record<ModelKey, string> = {
  opus: process.env.BEDROCK_MODEL_ID_OPUS ?? 'global.anthropic.claude-opus-4-6-v1',
  sonnet: process.env.BEDROCK_MODEL_ID_SONNET ?? 'global.anthropic.claude-sonnet-4-6',
  haiku:
    process.env.BEDROCK_MODEL_ID_HAIKU ??
    'global.anthropic.claude-haiku-4-5-20251001-v1:0',
};

const DEFAULT_REGION = process.env.AWS_REGION ?? 'us-east-1';
const OBSERVABILITY_DEBUG_LOG = process.env.OBSERVABILITY_DEBUG_LOG === 'true';

type GenerationConfig = {
  model: ModelKey;
  temperature: number;
};

const PRESETS: Record<ResponsePreset, GenerationConfig> = {
  fast: {
    model: 'haiku',
    temperature: 0.3,
  },
  balanced: {
    model: 'sonnet',
    temperature: 0.5,
  },
  deep: {
    model: 'opus',
    temperature: 0.7,
  },
};

const MODEL_TO_PRESET: Record<ModelKey, ResponsePreset> = {
  haiku: 'fast',
  sonnet: 'balanced',
  opus: 'deep',
};

const LENGTH_CONFIG: Record<LengthKey, { maxTokens: number }> = {
  short: { maxTokens: 1024 },
  normal: { maxTokens: 4096 },
  detailed: { maxTokens: 8192 },
};

function nowIso(): string {
  return new Date().toISOString();
}

function createTraceId(): string {
  return uuidv7();
}

function resolveConfig(
  preset: ResponsePreset,
  length: LengthKey,
): {
  modelId: string;
  region: string;
  temperature: number;
  maxTokens: number;
} {
  const base = PRESETS[preset];
  const tokenConfig = LENGTH_CONFIG[length];

  return {
    modelId: MODEL_IDS[base.model],
    region: DEFAULT_REGION,
    temperature: base.temperature,
    maxTokens: tokenConfig.maxTokens,
  };
}

const app = new BedrockAgentCoreApp({
  config: {
    logging: {
      options: buildLoggerOptions(),
    },
  },
  invocationHandler: {
    requestSchema: RequestSchema,

    process: async function* (request, context) {
      const userId = request.userId || 'dev-user';
      const threadId = request.threadId || `ephemeral-${createTraceId()}`;

      const session = await createRuntimeSessionManager({ userId, threadId });

      const effectivePreset = request.model
        ? MODEL_TO_PRESET[request.model]
        : request.preset;
      const agent = createRouterAgent({
        modelConfig: resolveConfig(effectivePreset, request.length),
        sessionManager: session.sessionManager,
      });
      const finalPrompt = buildRouterPrompt({
        userPrompt: request.prompt,
        tone: request.tone,
        commandDirective: request.commandDirective,
      });
      const traceId = request.traceId ?? createTraceId();
      const startedAt = nowIso();
      const observability = new ObservationCollector(
        traceId,
        startedAt,
        OBSERVABILITY_DEBUG_LOG,
      );
      const modelId = resolveConfig(effectivePreset, request.length).modelId;
      const logger = new RuntimeLogger(traceId, threadId, modelId, context.log);
      // Prefer the API-generated requestId from the payload — it matches the
      // value the client sees in the response and in DynamoDB. Fall back to
      // the BedrockAgentCore-supplied context.requestId when the caller did
      // not provide one.
      const effectiveRequestId = request.requestId ?? context.requestId;
      if (effectiveRequestId) {
        logger.setRequestId(effectiveRequestId);
      }
      const toolStartTimes = new Map<string, { name: string; startedAt: number }>();
      let currentStreamingToolUseId: string | undefined;
      let currentStreamingToolName: string | undefined;
      // Deck Live Preview captured from a create_slide_presentation result, to be
      // attached to the next artifact manifest the model emits.
      let pendingDeck: DeckResult | undefined;
      // Whether any *live* deck event was relayed this turn (#421). If streaming
      // was on but nothing streamed (e.g. the slide runtime wasn't streaming),
      // we fall back to the Route A replay so we never do worse than replaying.
      let relayedDeckEvent = false;

      logger.logInvocationStart({
        userId,
        sessionId: context.sessionId,
        preset: effectivePreset,
        length: request.length,
      });

      try {
        // Merge the agent stream with the slide-runtime's real-time deck events
        // (#421). With ROUTER_DECK_STREAMING off, the relay is inactive and this
        // simply forwards agent events (deck queue stays empty) — pre-#421 behavior.
        const { stream: merged } = createDeckMergedStream(agent.stream(finalPrompt), {
          relay: ROUTER_DECK_STREAMING,
        });
        for await (const item of merged) {
          if (item.source === 'deck') {
            relayedDeckEvent = true;
            yield {
              event: 'message',
              data: { type: 'deck_progress', event: item.event },
            };
            continue;
          }
          if (item.source === 'agent-done') {
            observability.onAgentMetrics(item.value.metrics);
            observability.finalizeMissingToolCounts();
            break;
          }

          const event = item.value;
          observability.logStreamEventType(event.type);

          if (
            event.type === 'modelStreamUpdateEvent' &&
            event.event.type === 'modelContentBlockDeltaEvent' &&
            event.event.delta.type === 'textDelta'
          ) {
            yield {
              event: 'message',
              data: {
                type: 'text',
                text: event.event.delta.text,
              },
            };
            continue;
          }

          if (
            event.type === 'modelStreamUpdateEvent' &&
            event.event.type === 'modelContentBlockDeltaEvent' &&
            event.event.delta.type === 'reasoningContentDelta'
          ) {
            observability.onReasoningDelta(event.event.delta.text);
            continue;
          }

          if (
            event.type === 'modelStreamUpdateEvent' &&
            event.event.type === 'modelContentBlockStartEvent' &&
            event.event.start?.type === 'toolUseStart'
          ) {
            const { toolUseId, name } = event.event.start;
            toolStartTimes.set(toolUseId, { name, startedAt: Date.now() });
            currentStreamingToolUseId = toolUseId;
            currentStreamingToolName = name;
            observability.onModelToolUseStart(toolUseId, name);
            logger.logToolCallStart(toolUseId, name);
            continue;
          }

          if (
            event.type === 'modelStreamUpdateEvent' &&
            event.event.type === 'modelMetadataEvent'
          ) {
            observability.onModelMetadataUsage(event.event.usage);
            logger.logModelUsage(event.event.usage);
            yield {
              event: 'message',
              data: {
                type: 'observation',
                observation: observability.createSnapshot('success'),
              },
            };
            continue;
          }

          if (
            event.type === 'contentBlockEvent' &&
            event.contentBlock.type === 'toolUseBlock'
          ) {
            observability.onContentToolUseBlock(
              event.contentBlock.toolUseId,
              event.contentBlock.name,
            );
            // Some tools arrive as a complete toolUseBlock rather than a streamed
            // `toolUseStart`, so toolStartTimes (populated only there) misses them
            // and the later toolResultEvent resolves toolName to 'unknown_tool' —
            // which silently skips deck capture / manifest attach. Record the name
            // here too (without clobbering an existing streamed start time).
            if (!toolStartTimes.has(event.contentBlock.toolUseId)) {
              toolStartTimes.set(event.contentBlock.toolUseId, {
                name: event.contentBlock.name,
                startedAt: Date.now(),
              });
            }
            continue;
          }

          if (event.type === 'toolStreamUpdateEvent') {
            const progress = event.event.data as SubAgentProgressEvent | undefined;
            if (progress && typeof progress.stage === 'string') {
              if (currentStreamingToolUseId && currentStreamingToolName) {
                logger.logSubAgentToolProgress(
                  currentStreamingToolUseId,
                  currentStreamingToolName,
                  progress.stage,
                  progress.status,
                  progress.durationMs,
                  progress.inputTokens,
                );
              }
              yield {
                event: 'message',
                data: {
                  type: 'observation',
                  observation: observability.createSnapshot('success'),
                  subAgentStage: progress,
                },
              };
            }
            continue;
          }

          if (event.type === 'toolResultEvent') {
            const { toolUseId } = event.result;
            const toolInfo = toolStartTimes.get(toolUseId);
            toolStartTimes.delete(toolUseId);
            if (currentStreamingToolUseId === toolUseId) {
              currentStreamingToolUseId = undefined;
              currentStreamingToolName = undefined;
            }
            const toolDuration = toolInfo ? Date.now() - toolInfo.startedAt : 0;
            const toolName = toolInfo?.name ?? 'unknown_tool';
            const toolStatus = event.result.status === 'error' ? 'error' : 'success';
            observability.onToolResult(toolUseId, toolStatus, event.result.content);
            if (toolStatus === 'error') {
              logger.logToolCallError(toolUseId, toolName, toolDuration);
            } else {
              logger.logToolCallEnd(toolUseId, toolName, toolDuration);
            }
            if (toolName === 'create_slide_presentation' && toolStatus === 'success') {
              const capturedDeck = parseDeckFromSlideResult(event.result.content);
              if (capturedDeck) {
                pendingDeck = capturedDeck;
                // Route A (Epic #403): replay the completed deck's progress so the
                // client reveals slides incrementally. With ROUTER_DECK_STREAMING
                // on (#421) the real per-slide events already streamed live through
                // the merge, so skip the replay to avoid duplicate events — but
                // only if we actually relayed something. If streaming was on yet no
                // live event arrived (e.g. the slide runtime wasn't streaming), fall
                // back to the replay so we never do worse than Route A. The
                // authoritative deck is still attached to the manifest below.
                if (!ROUTER_DECK_STREAMING || !relayedDeckEvent) {
                  yield* emitDeckProgressEvents(capturedDeck);
                }
              }
            }
            if (toolName === 'create_artifact_manifest' && toolStatus === 'success') {
              const manifest = parseArtifactManifestContent(event.result.content);
              if (manifest) {
                // Deterministically attach the captured deck (the LLM never sees
                // or copies the presigned-URL payload).
                const manifestWithDeck = attachDeckToManifest(manifest, pendingDeck);
                // Consume the captured deck once a manifest call has resolved, so
                // a stale deck can't ghost-attach to a later, unrelated manifest.
                pendingDeck = undefined;
                yield {
                  event: 'message',
                  data: { type: 'artifact_manifest', manifest: manifestWithDeck },
                };
              } else {
                // Manifest JSON was malformed; drop the captured deck rather than
                // letting it attach to a subsequent unrelated manifest.
                pendingDeck = undefined;
              }
            }
            yield {
              event: 'message',
              data: {
                type: 'observation',
                observation: observability.createSnapshot('success'),
              },
            };
            continue;
          }

          if (event.type === 'agentResultEvent') {
            observability.onAgentMetrics(event.result.metrics);
          }
        }

        const finalObservation = observability.createSnapshot('success');
        observability.logFinalSummary();
        const durationMs = Math.max(
          0,
          new Date(finalObservation.completedAt).getTime() -
            new Date(startedAt).getTime(),
        );
        logger.logInvocationEnd(durationMs, {
          tokenUsage: finalObservation.tokenUsage,
          toolCallCount: finalObservation.toolCallCount,
          toolFailureCount: finalObservation.toolFailureCount,
        });

        yield {
          event: 'message',
          data: {
            type: 'done',
            observabilitySummary: finalObservation,
          },
        };
      } catch (error: unknown) {
        const finalObservation = observability.createSnapshot('error');
        const message =
          error instanceof Error && error.message.trim().length > 0
            ? error.message
            : 'Runtime processing failed.';

        observability.logErrorSummary(finalObservation);
        logger.logInvocationError(error, {
          finalObservation,
        });

        yield {
          event: 'message',
          data: {
            type: 'error',
            error: message,
            observabilitySummary: finalObservation,
          },
        };
      }
    },
  },
});

app.run();
